---
version: '2.0'

brcd_openstack.deconfigure_trunk_vlan_on_interface:
  
  input:
    - switch_address
    - switch_username
    - switch_password
    - interface_name
    - interface_type
    - vlan
  tasks:

    notify_on_slack:
      # [105, 26]
      action: chatops.post_message
      input:
        channel: "lkhtesting"
        message: "Attempting to remove trunk VLAN <% $.vlan %> from interface <% $.interface_name %> of switch <% $.switch_address %>" 
      on-success:
        - remove_vlan_from_interface
      on-error:
        - report_failure
    remove_vlan_from_interface:
      # [175, 128]
      action: brcd_openstack.bwc_deconfigure_trunk_vlan_on_interface
      input:
        switch_address: <% $.switch_address %>
        switch_username: <% $.switch_username %>
        switch_password: <% $.switch_password %>
        interface_name: <% $.interface_name %>
        interface_type: <% $.interface_type %>
        vlan: <% $.vlan %>
      on-success:
        - send_success_msg_to_slack
      on-error:
        - untag_interface_failed 
    send_success_msg_to_slack:
      # [525, 740]
      action: chatops.post_message
      input:
        message: "Trunk VLAN <% $.vlan %> has been successfully removed from interface <% $.interface_name %> of switch <% $.switch_address %>"
        channel: "lkhtesting"
      on-error:
        - report_failure
    untag_interface_failed:
      action: chatops.post_message
      input:
        message: "Failed to remove VLAN <% $.vlan %> on interface <% $.interface_type %> <% $.interface_name %> of switch <% $.switch_address %>! Submitting a JIRA issue"
        channel: "lkhtesting"
      on-success:
        - create_jira_issue
      on-error:
        - report_failure
    create_jira_issue:
      # [638, 743]
      action: jira.create_issue
      input:
        type: "IT Help"
        summary: "Openstack VLAN add on interface failed"
        description:  "Failed to remove new Openstack network VLAN <% $.vlan %> to switch <% $.switch_address %>\n<% task(push_vlan_on_interface).result.stderr %>"
      on-error:
        - report_failure
    report_failure:
      # [145, 944]
      action: chatops.post_message
      input:
        message: "Something went wrong in removing VLAN <% $.vlan %> from interface <% $.interface_name %> of switch <% $.switch_address %>!"
        channel: "lkhtesting"
        
